# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlAuthVault < Formula
  desc "Kubectl plugin for Vault OIDC token authentication"
  homepage "https://github.com/efortin/kubectl-auth-vault"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/efortin/kubectl-auth-vault/releases/download/v0.0.2/kubectl-auth_vault_0.0.2_darwin_amd64.tar.gz"
      sha256 "f47e451df9d5aea6179a7660f8e1543d9bfd289c97ff07b6c67337b4543a59b7"

      def install
        bin.install "kubectl-auth_vault"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/efortin/kubectl-auth-vault/releases/download/v0.0.2/kubectl-auth_vault_0.0.2_darwin_arm64.tar.gz"
      sha256 "ec2a733ec01a8ab37a11788d3c0ce48748f3c2931ea758d56b863225bc0542c5"

      def install
        bin.install "kubectl-auth_vault"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/efortin/kubectl-auth-vault/releases/download/v0.0.2/kubectl-auth_vault_0.0.2_linux_amd64.tar.gz"
      sha256 "fd4e272f22ef649f005c93dda5a6539f50e704be083ead08d6acca29bf60fc0a"
      def install
        bin.install "kubectl-auth_vault"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/efortin/kubectl-auth-vault/releases/download/v0.0.2/kubectl-auth_vault_0.0.2_linux_arm64.tar.gz"
      sha256 "a1322e5c20214733b14445acf9935f73b6f864573d7cd569cffcc8d82ed2cc7f"
      def install
        bin.install "kubectl-auth_vault"
      end
    end
  end

  test do
    system "#{bin}/kubectl-auth_vault", "version"
  end
end
